### ISSUE TITLE
iemic todo

### ISSUE THREAD

**Issue by ipelupessy** [nlesc-smcm/spinup-benchmark#2]
this issue tracks things to fix in order to get the benchmark working for I-EMIC

- [x] a interface function for evolve_model() or equilibrate() to step in time and get the equilibrium solution (independent of continuation)
- [x] get mask of iemic (corrected one, used internally)
- [ ] wind, salinity and heat forcing settable through the interface
- [ ] write script with parameters and run and plot equilibrium
- [ ] fix units (by hand for now)

**Comment by ipelupessy** [comment]
wip!
